[mssql_servers]
172.16.11.135
172.16.11.136
172.16.11.137

[mssql_servers:vars] 
ansible_user=p05idon
ansible_become=yes
ansible_ssh_private_key_file=~/.ssh/id_rsa

# Variabel Konfigurasi Alloy
db_user=GrafanaMonitor
db_pass=admin123
prometheus_url=http://172.16.11.200:9090/api/v1/write
loki_url=http://172.16.11.200:3100/loki/api/v1/push