[mssql_servers]
172.16.11.200 ansible_user=student
172.16.11.201 ansible_user=student
172.16.11.202 ansible_user=student

[mssql_servers:vars] 
db_user=GrafanaMonitor
db_pass=admin123

[prometheus_loki:vars]
prometheus_url=http://172.16.11.200:9090/api/v1/write  
loki_url=http://172.16.11.200:3100/loki/api/v1/push  
